version: '1.0.{build}'
image: 
  - Visual Studio 2019
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
before_build:
  - cmd: dotnet restore
build:
  publish_nuget: true
  publish_nuget_symbols: true
  use_snupkg_format: true
build_script:
  - cmd: dotnet build -c Release /p:packageversion=%APPVEYOR_BUILD_VERSION%
test_script:
  - cmd: dotnet test
after_test:
  - cmd: dotnet pack -c Release -o artifacts --no-build
deploy:
  provider: NuGet
  api_key:
    secure: aWgBEnAfrZEZXu/7DZTbgzZiZNkSBMjrd7/bulCDHk+HUUDlxb3c67O4702scYaO
  on:
    branch: master 