version: '1.0.{build}'
image: 
  - Visual Studio 2019
environment:
  NugetPushApiToken:
    secure: L0Kw4cdsCTVEuIdk2Zs5cV78vv78V5BltFQ7FEbUI+cck+NBGRmSIxx8ciXQ6XLQ
  SonarScannerToken:
    secure: hv+y0yaBJXEcmrGlZTgdCo4VBN2TZH0mIhrZ7Q2NF8ZJ5mZg9UHHDOO9hh83Vv0N
build_script:
- ps: .\build.ps1
on_success:
- ps: .\publish.ps1
  on:
    branch: master 