version: '1.0.{build}'
image: Visual Studio 2019
branches:
  only:
  - master
build_script:
  - cmd: dotnet build -c Release
test_script:
  - cmd: dotnet test
after_test:
  - cmd: dotnet pack -c Release -o artifacts
  - cmd: appveyor PushArtifact "artifacts\UkooLabs.FbxSharpie.%APPVEYOR_BUILD_VERSION%.nupkg"