version: '1.0.{build}'
image: Visual Studio 2017
branches:
  only:
  - master
before_build:
  - cmd: dotnet restore
build_script:
  - cmd: dotnet build -c Release
  - cmd: dotnet pack -c Release
after_build:
artifacts:
 - path: '\UkooLabs.FbxSharpie\bin\Release'
test_script:
  - cmd: dotnet test