version: '1.0.{build}'
image: Visual Studio 2019
branches:
  only:
  - master
build_script:
  - cmd: dotnet build -c Release
test_script:
  - cmd: dotnet test
after_build:
  - cmd: dotnet pack -c Release
artifacts:
 - path: '**\*.nupkg'